# Generated by Django 2.2.12 on 2020-05-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200515_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='', upload_to='app/images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=50),
        ),
    ]
