# Generated by Django 2.2.12 on 2020-05-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200515_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='', upload_to='app/images/books'),
        ),
    ]
