# Generated by Django 2.2.12 on 2020-05-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200515_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(choices=[('Programming With C', 'c'), ('Programming With C++', 'cpp'), ('Programming With C#', 'csharp'), ('Programming With Java', 'java'), ('Programming With Python', 'python'), ('Compitition', 'compitition'), ('Comics', 'comics')], max_length=50),
        ),
    ]
