# Generated by Django 2.2.12 on 2020-05-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200516_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(choices=[('c', 'Programming With C'), ('cpp', 'Programming With C++'), ('csharp', 'Programming With C#'), ('java', 'Programming With Java'), ('python', 'Programming With Python'), ('compitition', 'Compitition'), ('comics', 'Comics')], max_length=50),
        ),
    ]
