# Generated by Django 2.2.12 on 2020-05-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200516_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, default='', upload_to='app/images/books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_publish',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
