# Generated by Django 2.2.12 on 2020-05-16 12:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200516_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_genere', multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Epics', 'Epics'), ('Horror', 'Horror'), ('Musicals', 'Musicals (Dance)'), ('Science', 'Science Fiction'), ('War', 'War (Anti-War)')], max_length=69)),
                ('movie_year', models.DateField(blank=True)),
                ('movie_quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], max_length=50)),
                ('movie_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50)),
                ('movie_category', models.CharField(choices=[('Bollywood', 'Bollywood'), ('Hollywood', 'Hollywood'), ('South', 'South')], max_length=50)),
                ('movie_language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Punjabi', 'Punjabi'), ('DualAudio', 'Dual Audio'), ('MultiAudio', 'Multi Audio')], max_length=50)),
            ],
        ),
    ]
