# Generated by Django 2.2.12 on 2020-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200516_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
