# Generated by Django 2.2.12 on 2020-05-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200521_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_subcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.Book_Category'),
        ),
        migrations.AddField(
            model_name='tutorial_subcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.Tutorial_Category'),
        ),
    ]
