# Generated by Django 2.2.12 on 2020-05-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200521_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='app.Book_Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_subcategory', to='app.Book_Subcategory'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tutoral_category', to='app.Tutorial_Category'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_subcategory', to='app.Tutorial_Subcategory'),
        ),
    ]
