# Generated by Django 2.2.12 on 2020-05-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200521_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Software_Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.Software_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=100)),
                ('software_description', models.TextField()),
                ('software_rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50)),
                ('software_url', models.CharField(blank=True, max_length=500)),
                ('software_image', models.ImageField(blank=True, default='', upload_to='app/images/software')),
                ('software_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='software_category', to='app.Software_Category')),
                ('software_subcategory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='software_subcategory', to='app.Software_Subcategory')),
            ],
        ),
    ]
