# Generated by Django 2.2.12 on 2020-05-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_software_software_category_software_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book_subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='software_category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='software_subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial_category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tutorial_subcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
