# Generated by Django 2.2.12 on 2020-05-22 18:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200521_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100)),
                ('series_genere', multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Epics', 'Epics'), ('Horror', 'Horror'), ('Musicals', 'Musicals (Dance)'), ('Science', 'Science Fiction'), ('War', 'War (Anti-War)')], max_length=69)),
                ('series_year', models.DateField(blank=True)),
                ('series_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50)),
                ('movie_language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Punjabi', 'Punjabi'), ('DualAudio', 'Dual Audio'), ('MultiAudio', 'Multi Audio')], max_length=50)),
                ('movie_description', models.TextField(blank=True)),
                ('movie_url', models.CharField(blank=True, max_length=500)),
                ('movie_image', models.ImageField(blank=True, default='', upload_to='app/images/series')),
            ],
        ),
    ]
