# Generated by Django 2.2.12 on 2020-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200522_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_category',
            name='category_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='book_subcategory',
            name='subcategory_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='software_category',
            name='category_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='software_subcategory',
            name='subcategory_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tutorial_category',
            name='category_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tutorial_subcategory',
            name='subcategory_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
