# Generated by Django 2.2.12 on 2020-05-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200523_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='software_rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='software_rating', to='app.Rating'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_rating',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_rating', to='app.Rating'),
        ),
    ]
