# Generated by Django 2.2.12 on 2020-05-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200523_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_category',
            name='category_url',
        ),
        migrations.RemoveField(
            model_name='book_subcategory',
            name='subcategory_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_url',
        ),
        migrations.RemoveField(
            model_name='genere',
            name='Genere_url',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language_url',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='quality_url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_url',
        ),
        migrations.RemoveField(
            model_name='software_category',
            name='category_url',
        ),
        migrations.RemoveField(
            model_name='software_subcategory',
            name='subcategory_url',
        ),
        migrations.RemoveField(
            model_name='tutorial_category',
            name='category_url',
        ),
        migrations.RemoveField(
            model_name='tutorial_subcategory',
            name='subcategory_url',
        ),
        migrations.RemoveField(
            model_name='year',
            name='year_url',
        ),
    ]
