# Generated by Django 2.2.12 on 2020-05-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200523_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genere',
            old_name='Genere_name',
            new_name='genere_name',
        ),
    ]
