# Generated by Django 2.2.12 on 2020-05-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200523_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_genere',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movie_genere', to='app.Genere'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_genere',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='series_genere', to='app.Genere'),
        ),
    ]
